import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/lib/providers/themeProvider";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <ThemeProvider>
          <main className="flex flex-col w-full">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
